services:
  mongo:
    image: mongo
    restart: unless-stopped
    ports:
      - ${DB_PORT}:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${DB_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}

  app:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app:cached
    command: poetry run python botish/bot/main.py
  scheduler:
    build: .
    restart: unless-stopped
    depends_on:
      - mongo
    env_file:
      - .env
    volumes:
      - .:/app:cached
    command: poetry run python botish/scheduler/main.py
